services:
  # 1. Base de Datos SQL Server
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "14333:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=El2026Admin.- # Cambia esto por una contraseña fuerte
    
  # 2. Microservicio de Products
  products-api:
    build: 
      context: ./backend/Products
    ports:
      - "5022:8080" # Mapea tu puerto 5022 al 8080 del contenedor
    depends_on:
      - sqlserver
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ProductsDB;User Id=sa;Password=El2026Admin.-;TrustServerCertificate=True;

  # 3. Microservicio de Transactions
  transactions-api:
    build: 
      context: ./backend/Transactions
    ports:
      - "5235:8080" # Mapea tu puerto 5235 al 8080 del contenedor
    depends_on:
      - sqlserver
      - products-api
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=TransactionsDB;User Id=sa;Password=El2026Admin.-;TrustServerCertificate=True;
      - ProductsUrl=http://products-api:8080/api/products/

  # 4. Frontend Angular
  angular-ui:
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - products-api
      - transactions-api